module.exports = {
    myepisodes: require('./myepisodes'),
    images: require('./images'),
    'swedish-hockey': require('./swedish-hockey'),
    'world-cup': require('./world-cup'),
    vasttrafik: require('./vasttrafik'),
    config: require('./config'),
    calendar: require('./calendar'),
    imageconf: require('./imageconf'),
    checksum: require('./checksum'),
    coop: require('./coop'),
    weather: require('./weather'),
    sonarr: require('./sonarr'),
    portainer: require('./portainer'),
    electricity: require('./electricity'),
    openings: require('./openings'),
    hemglass: require('./hemglass'),
};
