name: build-containers

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kokarn
          password: ${{ secrets.GHCR_PAT }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ghcr.io/kokarn/alluring-mirror:latest

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

    #   -
    #     name: Update container
    #     run: curl -k -X POST https://home.kokarn.com:9443/api/stacks/webhooks/0fc28bfa-8e18-4949-ac02-fe4a104f30f3
